"""
report_generator.py — PDF Report Generator for Heart Disease Prediction
Uses fpdf2 to create a clinical-style PDF report.
"""

import io
from datetime import datetime


def generate_pdf_report(
    patient_data: dict,
    risk_prob: float,
    risk_label: str,
    shap_vals: dict | None = None,
) -> bytes:
    """
    Generate a styled PDF report and return it as bytes.

    Args:
        patient_data: Dict of input feature names → values
        risk_prob: Float 0–1 risk probability
        risk_label: "HIGH RISK" or "LOW RISK"
        shap_vals: Optional dict of feature → SHAP value

    Returns:
        PDF as bytes (for st.download_button)
    """
    try:
        from fpdf import FPDF
    except ImportError:
        # Return a minimal plain-text fallback if fpdf2 is missing
        text = _plain_text_report(patient_data, risk_prob, risk_label)
        return text.encode("utf-8")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Header ────────────────────────────────────────────────────────────────
    pdf.set_fill_color(30, 30, 60)        # dark navy
    pdf.rect(0, 0, 210, 32, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_xy(10, 8)
    pdf.cell(0, 10, "CardioAI - Heart Risk Assessment Report", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(10)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%d %B %Y  %H:%M')}", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    # ── Risk Result ───────────────────────────────────────────────────────────
    r, g, b = (200, 30, 30) if "HIGH" in risk_label.upper() else (20, 150, 80)
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 14, f"  {risk_label}  --  Risk Probability: {risk_prob:.1%}", ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Patient Inputs ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(240, 240, 255)
    pdf.cell(0, 8, "Patient Input Summary", ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)

    col_w = [80, 110]
    pdf.set_fill_color(220, 220, 240)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(col_w[0], 7, "Parameter", border=1, fill=True)
    pdf.cell(col_w[1], 7, "Value",     border=1, fill=True, ln=True)
    pdf.set_font("Helvetica", "", 10)

    fill = False
    for k, v in patient_data.items():
        pdf.set_fill_color(245, 245, 255) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.cell(col_w[0], 7, str(k),  border=1, fill=fill)
        pdf.cell(col_w[1], 7, str(v),  border=1, fill=fill, ln=True)
        fill = not fill
    pdf.ln(6)

    # ── SHAP Explanation ──────────────────────────────────────────────────────
    if shap_vals:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_fill_color(240, 240, 255)
        pdf.cell(0, 8, "Key Risk Drivers (SHAP Values)", ln=True, fill=True)
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)

        sorted_shap = sorted(shap_vals.items(), key=lambda x: abs(x[1]), reverse=True)[:8]
        for feat, val in sorted_shap:
            direction = "+ Increases risk" if val > 0 else "- Decreases risk"
            color     = (200, 50, 50) if val > 0 else (30, 140, 80)
            pdf.set_text_color(*color)
            pdf.cell(0, 6, f"  {feat:<35} {val:+.4f}   {direction}", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_fill_color(255, 245, 200)
    pdf.set_draw_color(200, 150, 0)
    pdf.multi_cell(
        0, 6,
        "DISCLAIMER: This report is generated by an AI model for educational and informational purposes only. "
        "It does NOT constitute a medical diagnosis. Always consult a qualified healthcare professional "
        "before making any health-related decisions.",
        border=1, fill=True,
    )

    # Return PDF as bytes
    return bytes(pdf.output())


def _plain_text_report(patient_data, risk_prob, risk_label):
    lines = [
        "CardioAI - Heart Risk Assessment Report",
        f"Generated: {datetime.now().strftime('%d %B %Y %H:%M')}",
        "=" * 50,
        f"RESULT: {risk_label}",
        f"Risk Probability: {risk_prob:.1%}",
        "=" * 50,
        "Patient Inputs:",
    ]
    for k, v in patient_data.items():
        lines.append(f"  {k}: {v}")
    lines.append("\nDISCLAIMER: For educational purposes only. Consult a doctor.")
    return "\n".join(lines)
